[region]
name = Sandbox
grid_x = 1000
grid_y = 1000
public_endpoint = http://sandbox.homeworldz.com:42001
http_port = 42001
viewer_port = 42002
bind_address = 0.0.0.0
viewer_bind_address = 0.0.0.0
data_path = var/region
asset_path = assets/region
terrain_path = assets/region/terrain/plateau-square.raw
lease_seconds = 60

[grid]
url = http://127.0.0.1:80
public_url = http://sandbox.homeworldz.com
# Use the same value as grid-cloud.ini.
service_token =
